name: primeiro-CI
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Get the code
      uses: actions/checkout@v4.1.5
      
    - name: Authentication on Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: build and push Docker Hub
      uses: docker/build-push-action@v6
      with:
        context: /src
        file: ./src/Dockerfile
        push: true
        tags: |
          pabloapache/aula-primeira-pipeline:v${{github.run_number}} ## increment one
          pabloapache/aula-primeira-pipeline:latest
    
      
    
      
    
